### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by Ged2323** [SwiftKitz/Notificationz#2]
Hi I have been trying to get this work though haven't been able to get the notifications to trigger other devices.  That what the notifications are meant to do right?

Thanks in advance for your help.

**Comment by ghost** [comment]
I don't think this is the right project to "trigger other devices". It's basically a helper library to make usage of NSNotificationCenter easier and simpler. Have a look at the [official documentation of NSNotificationCenter](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSNotificationCenter_Class/):

> An NSNotificationCenter object (or simply, notification center) provides a mechanism for broadcasting information within a program

So notifications take place inside the same app.

**Comment by Mazyod** [comment]
Thanks @volkanx for the explanation, you're absolutely right.
